ADD: proposal
Consamables/FoodBook pull request #1
Opened 2016-10-31 23:56 UTC by segerphilip

2016-10-31 23:58 UTC, wolfd requested changes

2016-10-31 23:58 UTC, wolfd commented on Proposal.md
> +## For each team member: three project learning goals. Explain what you hope to get out of the project and how your project will help accomplish that goal
Can we split this into multiple lines?

2016-11-01 00:00 UTC, segerphilip commented
Made changes

2016-11-01 00:01 UTC, sammyers approved these changes
This looks good now.

2016-11-01 00:01 UTC, wolfd approved these changes

2016-11-01 00:02 UTC, merged